### PR TITLE
Update to angular 2.0.0

### PR DESCRIPTION
**Pull request by frankadrian**
Let me know if you also want to upgrade Typescript to version 2 as in https://github.com/angular/quickstart/commit/d3a977e900f0ab25ec57e54f5be9e6184f5e44d5

### CODE REVIEW

**Comment by nimaen** [comment]
Thank you for your PR, can you please keep only one commit ?
Since you're updating to angular 2, there's no need to keep a rc7 commit 😉

**Comment by frankadrian** [comment]
Sure, just squashed the commits!

**Comment by nimaen** [comment]
Thanks !
I'll test it between 12pm and 2pm.

**Comment by nimaen** [comment]
Have you tried a simple `npm start` ?
I've got some zone issues with your branch.

**Comment by frankadrian** [comment]
Sorry, only saw your comment now! I'm going to have a look at this now!

**Comment by frankadrian** [comment]
Hmm, it is working for me! I also removed the node_modules and typings directory, ran `npm install` just to be sure. Can you try these steps and report if the problem still exists?

**Comment by nimaen** [comment]
Still no chance, I'll have another attempt tonight :)

**Comment by pumano** [comment]
any news about 2.0 support?

**Comment by nimaen** [comment]
Ok, I've been tricked by the demo folder.
Your PR is good, but the demo is not working since the static demo zone.js file is not updated.
I've created an issue to only use node_modules files, not static files.
Please add the new zone.js file in the demo/vendor path for the time being.
Otherwise, GJ 👍 

@vladotesanovic : this is really problematic, we should really check #80.

**Comment by nimaen** [comment]
Done in https://github.com/vladotesanovic/ngSemantic/commit/7a0857f8df0ac664843ca48b301883ed48ec7364

**Pull request closed without merging**
