### PR TITLE
Update to rc6

### PR DESCRIPTION
**Pull request by frankadrian**
Updated to rc6 according to https://github.com/angular/angular/blob/master/CHANGELOG.md

I think its worth thinking about creating a separate module for each component. Please let me know what you think!

### CODE REVIEW

**Comment by frankadrian** [comment]
Something seems to be broken with the travis setup!

**Comment by vladotesanovic** [comment]
@frankadrian Yes that is true, i will work on it to fix it in proper way.

I will review your code tonight from PR

**Comment by nimaen** [comment]
Seems like no `postinstall` rule is defined to run the typings `script`.
And I'm not so sure why you're installing stuff globally in the `.travis.yml` config @vladotesanovic.
You could just run npm scripts since they're already installer locally 😄

**Comment by frankadrian** [comment]
Some how the demo throws errors compiling the templates. Please see 62e1402 for an example in form and message components. 
Does anyone know the cause of this?

**Comment by nimaen** [comment]
I think you're mistaking things here.
Both modal and message components are defining content projection like this :

```html
<ng-content select="message-header"></ng-content>
```

This means that you have to use a `<message-header></message-header>` container, not a `<div class="message-header"></div>`.

**Comment by frankadrian** [comment]
Then why do i get this error:
`zone.js:461 Unhandled Promise rejection: Template parse errors:
'message-header' is not a known element`

**Comment by nimaen** [comment]
I took 30 minutes to investigate but could not find anything except this : https://github.com/angular/angular/issues/11251
I had the same problem in another project : It was because I was not properly export / importing the module. You might be able to make it works by replacing all custom `<modal-content>` and stuff with classes indeed.
Finally, I could solve this with webpack on my other project, but don't know why :)

**Comment by nimaen** [comment]
Forget what I said about webpack solving this issue : angular was still from the rc5 cache 😱

**Comment by frankadrian** [comment]
Thanks for your time @nimaen!
That was indeed the same problem i was facing. I could bypass it now by adding this to my app's ` schemas:   [ CUSTOM_ELEMENTS_SCHEMA ], ` module definition. This also worked for the demo, see: 1b6ae2c

**Comment by nimaen** [comment]
You're welcome !
I'm highly interested in this repo, that's why I'm starting to be active 😄 
Yeah indeed, already saw your commit ;)
Waiting for the boss merge then (still need to fix this travis thing, I'll do a PR for this).

**Pull request merged**
