### PR TITLE
Dropdown with icon

### PR DESCRIPTION
**Pull request by sguiheux**
Add icon in dropdown title like here: http://semantic-ui.com/modules/dropdown.html#pointing

### CODE REVIEW

**Comment by nimaen** [comment]
Can you squash your commits please :) ?

**Comment by sguiheux** [comment]
done :)

**Comment by sguiheux** [comment]
any news of when it will me merged?

**Comment by vladotesanovic** [comment]
@sguiheux I am back to work, i ll take a look on this ASAP

**Comment by sguiheux** [comment]
Someone here ? project is dead?

**Comment by vladotesanovic** [comment]
No it is not, i will marge all PR and changes

**Comment by sguiheux** [comment]
great :)

**Comment by AJRedDevil** [comment]
I tried the example of dropdown with icon and it didn't work. It always displays the pointing icon. I made the changes in the library file to update it locally but in production it won't work. When will we be able to change the dropdown  icon?

**Comment by sguiheux** [comment]
Try the dropdown icon with my fork if you want: 
"ng-semantic": "https://github.com/sguiheux/ngSemantic/tarball/master".
I'm using it and it works well.

**Comment by AJRedDevil** [comment]
@sguiheux Thanks, your code works but I need it in production and it would be easier if I could incorporate it in package.json. Is there a way to do so?

**Comment by sguiheux** [comment]
I need it in production too.
/Waiting for @vladotesanovic to merge it... since 7/10

**Comment by AJRedDevil** [comment]
@sguiheux Hopefully @vladotesanovic merges it soon.

**Pull request merged**
