### PR TITLE
added SemanticAccordion components

### PR DESCRIPTION
**Pull request by thuey**
I know I would still need to create a demo entry for this, but I noticed you were also working on the accordion, and I wanted you to be able to take a look at my accordion implementation. My team and I are really interested in adding angular2 support for semantic. Your repo seemed further along than anything else out there, so if you're interested, we could work on this together to get it feature complete.

### CODE REVIEW

**Comment by vladotesanovic** [comment]
That would be great.
I see that you use semantic.d.ts typings ( i removed that ), and i will remove typings folder from repo too.

What is benefit of having AccordinationTitle and AccordinationContent in separate components? 

This @Input ('accordionOptions') is good approach for bridging jquery api and semantic components. I will try to implement and use that.

**Comment by thuey** [comment]
I debated about whether or not to have AccordionTitle and AccordionContent.
What it boiled down to, is that I wanted to make it easier for the user to
not have to remember to add the classes that Semantic UI requires to be
present every time they want to use one of the components. I also wanted to
encapsulate the implementation, so that if Semantic UI changes the names of
those classes, they just have to be changed on those Components in
ngSemantic, instead of the end user replacing the classes throughout their
entire project. The Ionic Framework takes a similar approach, and it has
worked out well. However, Ionic is a bit too aggressive imo. It adds
classes that are not required, too, that affect the behavior of their
directives. My intent was to allow users to define any optional classes
they want, but to make sure we add the core classes for them.

Why did you decide on the name accordination instead of accordion?

**Comment by vladotesanovic** [comment]
No reason, and you are right, i will change name of this module.

Problem with inner components, like: AccordionTitle, AccordionContent inside AccordionItem inside AccorionElement... is that they add lot of shadow DOM elements. 
Semantic UI often use pseudo classes like ':first-element, .clas1 + clas2... ' And things often not work without changing viewEncapsulation in Angular2 or css customization.

**Comment by thuey** [comment]
I see your point, but I think it's okay if all of the components have viewEncapsulation set to `None`. ngSemantic already relies on global stylesheets for Semantic UI's styles. But I just started on this, so I might be misunderstanding the problem.

**Pull request closed without merging**
